### ISSUE TITLE
Exit key could work as previous menu or close menu

### ISSUE THREAD

**Issue by guirossibrum** [c3d/DB48X-on-DM42#1009]
This not a bug but a usability possibility. 
I need to get used with not clicking the exit menu while in program mode to return to the previous menu or sub menu. The program is discarded and all the work is lost.
I know there is a return menu button, but I guess it could be useful if the exit worked ans return menu and only cleared the program when all menus are closed. Just an idea. 

Thanks

**Comment by c3d** [comment]
The `EXIT` key quits the current object being edited in all HP RPL calculators that I can put my hands on. I believe it would be too much of a departure from the classical RPL UX to change it into a "back menu" when editing, even more so knowing that there is an actual "back menu" key.

The good news is that "the work is lost" is not true on DB48X (unlike HP calculators) because you can use the `HIST` entry to get the last editor entries.
