### ISSUE TITLE
Result of StandardDeviation is wrong

### ISSUE THREAD

**Issue by prismv** [c3d/DB48X-on-DM42#1103]
I recognize in the code that `StandardDeviation` and `PopulationStandardDeviation` are available and the respective variances.

I guess the former is the sample std.dev. (using dof=n-1) and the latter uses n as denominator for variance calculation.

Inserting sum data vector [1 2 6] in STAT gives the right total of 9 and mean of 3, and should give a standard deviation of (evaluated) `sqrt(7)`, i.e. 2.64575..., but the result is 2.3452... 

Just for completeness the population std.dev. should be (evaluated) `sqrt(4 2/3)`, i.e. 2.1602...

**Comment by c3d** [comment]
The bug is a little subtle.

I was trying to optimize away a sum with zero for the first term in the sum, but as a result I was skipping the call to the callback for that term. In the case of the variance, the callback was doing more than just the sum, it was computing the square of the difference to the average.

**Comment by c3d** [comment]
Good catch, @prismv, thanks a lot for reporting. Will be fixed in 0.7.14.

**Comment by prismv** [comment]
De rien. Thnx for the fast fix!
