### ISSUE TITLE
Saving state in iOS throws a failed message 

### ISSUE THREAD

**Issue by nickapos** [c3d/DB48X-on-DM42#1178]
While trying to save or load a state in iOS I get save state failed message or load state failed. 
however a state file is created in the iPhone. 
not sure if the state file is corrupted because load also throws the failure message.

**Comment by c3d** [comment]
Thanks for the report, @nickapos.

We are in the usual WorksForMe™ situation, so I guess I need to ask for more details.

Can you tell me:
- What application are you using as reported by going to the `SETUP` screen (SHIFT-0) and then selecting `2. About`
- What is the exact sequence of operations to get the message, in both the "save" and "load" cases?
- What is the exact error message? Ideally a screen capture. Asking because there is no exact match, and fuzzing matches different possibilities.
- What iPhone model you use, and what version of iOS?
- Where are you trying to save the file? Is it on iCloud or local storage?
- What happens if you enter `0` and  `"FILE"` on the stack, and then hit the `STO` key?

Thank you in advance for your answers.

**Comment by nickapos** [comment]
Hi Christophe, here are the screenshots

![IMG_3077](https://github.com/user-attachments/assets/931a4542-823d-4e1e-83b2-f9cba136305e)
![IMG_3078](https://github.com/user-attachments/assets/c53c50af-7ec6-4f7f-98d8-88769cbbcee1)
![IMG_3076](https://github.com/user-attachments/assets/55bb5e55-e3c5-4dc4-b86a-d4fb7f85957b)
I am using an iphone 15 plus with iOS version 17.6.1

**Comment by nickapos** [comment]
When i type 0 and 'FILE' and hit STO then i get no errors. It looks like FILE variable gets value 0

**Comment by c3d** [comment]
> When i type 0 and 'FILE' and hit STO then i get no errors. It looks like FILE
> variable gets value 0

Yes, but this is not the correct test case.

I asked about using `"FILE"` and not `'FILE'` (double quote instead of single quote). This stores in a file instead of a variable.

**Comment by c3d** [comment]
In the screenshots, I see no iOS file dialog. Did you see that prior to seeing the screen you show?

**Comment by nickapos** [comment]
Yes the dialog opens to allow you to type in the name of the state file for save or to,choose which file to load.

**Comment by nickapos** [comment]
Apologies about the FILE test. I did it again and got the following
![Screenshot 2024-09-14 at 07 43 17](https://github.com/user-attachments/assets/332004a7-c962-4a21-a98a-0db43a11f798)

**Comment by c3d** [comment]
> Apologies about the FILE test. I did it again and got the following 

Thanks. That's helpful, as it gives me the source of the problem.

The calculators these are modelled after (SwissMicros DM32 and DM42) can only open one file at a time. It's a limitation of their built-in firmware. So there is a lot of internal logic to close one file and open the next one in case I need to deal with two files at the same time, e.g. when processing constants in equations, the constants may have units, so you end up juggling with three files.

What the `Too many open files` message indicates is that this logic is somehow violated in your configuration. I need to explore the code to see how this could happen. If I can't find it, I will add some code in the next release to capture what could cause the problem.

I suspect that the problem might be with something specific to your config (in `Demo1`). When the calculator starts, it tries copying `units.csv`, `config.csv` and `equations.csv`, as well as the help files, from the application resources to a user-visible application directory. This is to allow you to edit these files.

When you use the Load state dialog, you told me you see the iOS dialog. My expectation is that it should be in a place called `state`. Please try to verify all the expectations below, and tell me if any of my expectations is not true.

On the left, you should have a blue text (a button) that looks like `< DB48X`. If you go there, you should see four folders: `config`, `data`, `help` and `state`. You should be able to go one level up, and see folders for various applications. One level up, and it should show you a dialog with various places, including `iCloud Drive` and `iPhone` (the exact text depends on localization). Normally, the folders you saw before should be on your local storage, i.e. down the `iPhone` path.

If you go back to the `DB48X` folder, then `config`, you should see 5 files (`characters`, `constants`, `equations`, `library` and `units`). If you modified any of these files yourself, please send me your copy, as this might play a role.

Inside the `DB48X` folder, there is also a `data` folder, which should contain your `FILE` test  file if things worked properly. Because of the error above, chances are that the folder is empty. For me, it contains just `FILE` which is one byte long.

Inside the `DB48X` folder, there is also a `help` folder, with three files and an `img` subfolder.

Finally, inside the DB48X folder, there is a `state` folder. That's the one where interesting stuff can be found. For all the files that are in there (and primarily the one called `Demo1` per your screenshot), can you select the file, use the "Share" button, then "Copy", then paste as a comment in this issue?

My suspicion is that there is something in this file that sends me down a path that is leaving a file open that should be closed (probably an error path that I forgot to cover, even if I did my best to use C++ constructors/destructors to deal with this).

**Comment by nickapos** [comment]
Hi Christophe, you are absolutely right in all of your assumptions, except the one that i might have modified any of these files. I did not know that i could modify anything so i have not done it.
Here are the screenshots from my phone and the Demo1 state you requested
![IMG_3091](https://github.com/user-attachments/assets/eea3db3c-f2d1-41e1-9039-631cf8f11818)
![IMG_3090](https://github.com/user-attachments/assets/92c28d88-e2b2-4359-8921-ea791ab5f2d5)
![IMG_3089](https://github.com/user-attachments/assets/d6c30c42-8a71-40a5-9629-88ecdb497d22)
[Demo1.zip](https://github.com/user-attachments/files/17010173/Demo1.zip)

I have zipped the state file because otherwise github does not allow me to submit it.

**Comment by c3d** [comment]
Did you by any chance install two distinct versions of DB48X, e.g. DB40X and DB50X?

**Comment by c3d** [comment]
The reason I asked is because I could reproduce somewhat similar symptoms by picking up the directory for another application, which has the same structure (e.g. trying to load the files from DB40X from DB50X).

Though the internal message is a permission denied error, I suspect that this could lead down a path where a file is not properly closed.

**Comment by nickapos** [comment]
No I only got DB48X

**Comment by nickapos** [comment]
This is interesting. I did a test. I was getting the same behaviour in my iPad. In both cases the app was installed at the same day and has been updated for a while automatically.
So I removed the app and reinstalled it. Now the problem is gone. I can save and load without this error.
I did the same to my iPhone and got the same results.

**Comment by c3d** [comment]
That seems to confirm my hunch that the problem is related to some permissions accessing the files. iOS does really bizarre things with the sandboxed paths. What shows as a nice DB48X folder on your local storage has an entirely different name internally, and is sandboxed so that one app cannot modify the data for another.

I added some code to show the actual OS-level error message in the message and the name of the file being accessed. That will be available in the next update.

**Comment by c3d** [comment]
I believe that I have found and fixed a number of issues that could result in the symptoms you observed. At the very least, you should now have better error messages such as "Permission denied" when a problem occurs.

This should become available in 0.8.0.
