### ISSUE TITLE
Error writing the state file when it contains constants

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#1267]
When saving the state file, we have two open files, the save file and the constants or equations or library file.

Since having two open files is not allowed on DMCP, the simulator catches it and
does not open the second file. As a result, the constants, xlibs or equations written on disk can only take the built-in ones into consideration, the index lookup is wrong, and so the wrong name is written. The write appears successful, since not being able to read the configuration files is not considered a fatal error. It only shows up in the logs.

**Comment by Wiljea** [comment]
Since opening a single file at a time constitutes a difficulty here which in turn requires a wealth of programming tricks, not to mention the execution time and the scheduling order management of the various temporary caches, etc. Would it not be appropriate for this restriction to be lifted? And to ask the designer of DMCP5 if such an evolution is possible? Certainly a one-dimensional platform like that of the RPN DMxx calculators (which probably only opens one state file at a time) is in stark contrast to the potentially multi-layered approach of the RPL environment. I wonder what it is about the Plus42 simulator that perhaps handles simultaneous file openings.
