### ISSUE TITLE
A SUM that doesn't evaluate

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1285]
According to ref. https://en.wikipedia.org/wiki/Pendulum_(mechanics)#:~:text=measured%20in%20metres.-,Arbitrary%2Damplitude%20period,-%5Bedit%5D
the real period of a pendulum can be computed up to fifth order using the following sum:
'(Treal_s)=2·Ⓒπ·√((L_cm)/Ⓒg)·(Σ(x;0;5;((2·x)!÷((2↑x)·x!)²)²·sin(θmax÷2)↑(2·x)))'

The problem is that the SUM alone doesn't evaluate and gives (with θmax = 90°):
   'Σ(x;0;5;((2·x)!÷(2↑x·x!)²)²·sin(θmax÷2)↑(2·x))'  "=" gives 
'((x!²)⁻¹)²+0.5·(2÷(2·x!)²)²+0.25·(24÷(4·x!)²)²+0.125·(720÷(8·x!)²)²+0.0625·(40 320÷(16·x!)²)²+0.03125·(3 628 800÷(32·x!)²)²'    OR

   'Σ(x;0;5;((2·x)!÷(2↑x·x!)²)²·sin(θmax÷2)↑(2·x))'  →NUM gives
[35819115 2659.041429] errors: Error [Out of memory]
[35825065 2659.054488] errors: Error [Out of memory]
[35860242 2659.150506] errors: Error [Bad argument type]
[35911473 2659.191570] errors: Error [Bad argument type]

If you try the zeroth order term:
   'Σ(x;0;0;((2·x)!÷(2↑x·x!)²)²·sin(θmax÷2)↑(2·x))'  "=" gives '((x!²)⁻¹)²'

where x! is italicised in the simulator. It's like if the calculator doesn't know how to compute this factor. If we get rid of this x! in the denominator the sum is evaluated to 1 which makes sense. But this is not what is needed.

**Comment by c3d** [comment]
The problem is that `x!` incorrectly parses as a name `x!` and not as the factorial of `x`.

The reason for that is that `!` is apparently accepted in names on the HP48 to some extent, and that made me incorreclty deduce that this was valid in an RPL name.

More experimentation showed that:

* The HP48SX parses `ABC!DE` as two names, `ABC!` and `DE`. This is different from `ABC?DE` that parses as a single name.

* The HP50 parses `ABC!` as `ABC !` (factorial of `ABC`) in a program. So `!` is no longer part of the name.

DB48X will now adopt the HP50G behaviour, which seems a bit saner, and reject `!` in a symbol.
