### ISSUE TITLE
"Inconsistent units" in Electricity

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1349]
If you try 1_F·V/s BASE you obtain A, which is correct. But with the following value:
2.97832 74271 5⁳⁹ pF·V↑2/V∗s  1_mA  CONVERT you will get "Inconsistent units".

**Comment by c3d** [comment]
There are two errors in the expression:

1/ The expression contains the wrong character for multiplication `∗`. This is Unicode 8727, not the normal multiplication operator `*` (Unicode 42). I suspect that this was copy-pasted something from some Windows application that tries to be smart with Unicode. If you copy-paste this in the calculator or simulator, the character does not show up, and the unit looke like `Vs`, although there is an invisible character in the middle.

2/ Even with the correct multiply sign, the unit is still wrong because you multiply by `s` instead of dividing. It should be `_pF·V↑2/(V*s)` and not `_pF·V↑2/V*s`.


After correction, this works:
```rpl
2.97832 74271 5⁳⁹ pF·V↑2/(V*s) 1_mA CONVERT
2.97832 74271 5 mA
```

Closing as user error.
