### ISSUE TITLE
Issue with `DOT` command and a suggestion

### ISSUE THREAD

**Issue by skai111** [c3d/DB48X-on-DM42#1363]
DB50X v.0.8.6-11-b68dZ
Hardware DM42n

DB50X permits DOT to operate on 2D arrays, or Matrixes.

If it is allowed to operate on 2d-arrays, then there is an issue with restoring of stack upon non conforming arrays:

``` rpl
[[1 2 3][4 5 6]] [[1 2][3 4][5 6]]  DOT
```

This yields: `1` and `4` on the stack, with an error `DOT error: Invalid dimensions`. The stack is not restored.

Usually DOT is not defined for 2D arrays. I don't know what happens if it is a
tensor.

Suggestion to forbid this unless a flag specifically allow for this, and it is
clearly defined in the user guide.
**Rationale**:  memory allocation on all HP48, 49,50 calculators are row wise like in C. Not columnwise like in fortran. There is no speed gain,but consider to allow `DOT` to operate on list of vectors.

``` rpl
{[ 1 2 3]
[ 4 5 6 ]}
{[ 1 2 3]
[ 4 5 6 ]}
DOT
```

with expected result `{14 77 }`

**Comment by c3d** [comment]
Thanks @skai111 for the input and report.

Except for the botched stack restoration, the behavior is expected and documented. The rationale for it is given [in the documentation][mat-diff].

Here is a relevant quote explaining the rationale:

> The application of a same operation on arrays or matrices has never been very consistent nor logical across RPL models from HP.

This part of the documentation highlights inconsistencies across operations in a same calculator, or for the same operation, across HP models. In order to bring some order to that chaos, I spent a bit of time thinking about what the data types actually meant, and I reached the following general conclusions:

1. Lists are for ordered sequences of arbitrary data, where arithmetic operations apply to the list items as opaque data, not taking their precise value into account. Therefore, `{ 1 2 } 3 *` is `{ 1 2 1 2 1 2 }`, and `{ 1 2 } 3 +` is `{ 1 2 3 }`. There is no attempt to treat items as numerical. For example, there is no separate `Add` command with a behaviour that differs from `+` (which IMHO was an abomination)...

2. On the contrary, arrays are intended to carry numerical values and perform global numerical operations. Therefore, `[ 1 2 ] 3 *` is the vector multiplication, resulting in `[ 3 6 ]`, and `[ 1 2 ] 3 +` is `[ 4 5 ]`. The addition is an extension relative to all HP models, but is perfectly consistent with common usage in mathematics.

3. In that context, matrices are simply vector of vectors, and it takes very few special rules to get the correct result "for free". The exact same code can then be used for vector or matrix operations.

With that approach, something like `[ 1 [2 3]] [[4 5] 6] +` is now perfectly defined and returns `[[ 5 6 ] [ 8 9 ]]`. The code also does meaninful and potentially useful operations on vectors containing non-numerical objects. For example, you can do a dot product with text items, and `[ "A" "B" ] [ 2 3 ] dot` gives `"AABBB"`, which is simply `"A" 2 * "B" 3 * +`.

Now, let's apply this to your example:

``` rpl
[[1 2 3][4 5 6]] [[1 2][3 4][5 6]]  DOT
```

The rules of the dot product cannot apply to the outer vector, because the first vector has 2 items and the second three. So the `Invalid dimensions` message is correct.

If we adjust the dimensions as follows, then we get an interesting result:

``` rpl
[[ 1 2 3 ] [ 4 5 6 ]]
[[ A B C ] [ D E F ]]
DOT
```

This produces `[ 'A+4·D' '2·B+5·E' '3·C+6·F' ]`. Why? Because we perform `[1 2 3][A B C] * [4 5 6][D E F] * +`. Then we have `[A 2*B 3*C] [4*D 5*E 6*F] +`, and this gives the final result.

Now, regarding your desire to apply `DOT` to multiple pairs, it is trivially achieved as follows:

``` rpl
{ [1 2 3] [4 5 6 ]}
{ [1 2 3] [4 5 6 ]}
2 «DOT»
```

This gives `{ 14 77 }` as you wanted.


[mat-diff]: https://github.com/c3d/db48x/blob/stable/help/db48x.md#vectors-and-matrices-differences

**Comment by skai111** [comment]
Thanks for explaining. Hopefully it can put it to good use. 👍
