### ISSUE TITLE
Parsing error of negative constants

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1373]
For instance the neutron magnetic moment (like 3 other constants) has a negative value. The usual way to specify it in the "Constants.cc" file would be:
"μn",       "−9.6623653E-27_J/T"  but this  leads to  '→NUM(Ⓒμn)'=−9 
which is not even a number.

The only way that I found to circumvent this problem is to write the operation:
"μn",       "'(-1)*9.6623653E-27_J/T'" => '→NUM(Ⓒμn)'=-9.66236 53000 0000⁳⁻²⁷ J/T
which is what was intended

**Comment by c3d** [comment]
I am afraid that we have Notepad to blame again ;-)

I copied your code:

``` c++
"μn", "−9.6623653E-27_J/T"
```

and indeed, this does not work. What you get on the stack is `−9`. If you look carefully, you will noticed that it shows as _italics_. This is a hint. It indicates that we have a _symbol_, not a number. And indeed, if we check with `TypeName`, the result is `"expression"`, not `"decimal"` or `"neg_integer"`.

So what is going on?

The first character in your expression is `−` (Unicode 8722) and not `-` (Unicode 45). So the parser creates a name with it. It's `−9` much like you would have `A9`.

I will add an exclusion rule so that the characters that Notepad keeps helpfully generating for you are no longer silently accepted. They will now flat-out be rejected with a syntax error.

Meanwhile, to keep going, use this:

``` c++
"μn", "-9.6623653E-27_J/T"
```

**Comment by Wiljea** [comment]
It must be a problem of working in the Win10 environment because not only I didn't use NotePad++ but I was copying and pasting strictly between the open file (in edition mode) constants.cc (on GitHub) directly to the simulator via CTRL C, CTRL V. I am not working in NotePad++ anymore since I am doing Commits as often as needed.
