### ISSUE TITLE
Combinations with hwfp does not return Inf, if applicable

### ISSUE THREAD

**Issue by prismv** [c3d/DB48X-on-DM42#1392]
When HwFP is enabled, entering 2E929 gives infinity (as expected).

9999 555 COMB would return a decimal result of the same order of magnitude as the previous input, i.e. 2.24471E929, but the operation fails silently - as if COMB had not been pressed - if HwFP is set.

**Comment by c3d** [comment]
This does not match my experience. For `9999 555 COMB`, I get `∞` with `hwdouble` or `hwfloat` types with precision 16 and 7 respectively, with an error message `Number is too big`. Just tested on the `dev` branch.

On the other hand, `9999. 555. COMB`, i.e. using decimal dot, gives the wrong result `1`. This is due to the symbolic simplification `X/X=1` applying to the case where `X` is `Inf`. The correct result should be `NaN` for the division. But that does not match your description either, i.e. it does not fail silently.

**Comment by c3d** [comment]
Can you copy here the result of the `MODES` command?

**Comment by prismv** [comment]
About shows actual HEAD hash: v0.8.8-9-a1f5Z

MODES gave:

```
«
	NUMERICALRESULTS NOAUTOSIMPLIFY
	COMPLEXRESULTS OVERFLOWINDICATOR
	BEEPOFF SILENTBEEPON
	INDEXWRAPPED HARDWAREFLOATINGPOINT
	5 SIG 5 DISPLAYDIGITS
	5 STANDARDEXPONENT 16
	PRECISION UPPERCASE
»
```

**Comment by prismv** [comment]
Tested this with 5572b7a2 as successor of 3a0a1c04, but `9999 555 COMB` still fails silently!

Edit: This happens still on DM42. In simulator result is 0.

**Comment by skai111** [comment]
DB50X v. 0.8.8
HW DM42n
This may be hardware related due to Hardware floating point handling. 

This may be due to overflow of intermediate results, or possibly that the standard for HwFP "gracefully" extend limited precision at boundaries. Consider following example with single precision.
1)  set HwFP 5 Prec -100 exp  // natural antilogaritm
result 3.784e-44
2) deselect HwFP 5 Prec -100 exp
result 3.722e-44


Similar with double precision, but larger numbers of course.
