### ISSUE TITLE
Issue with HwFP , matrix DET calculation

### ISSUE THREAD

**Issue by skai111** [c3d/DB48X-on-DM42#1393]
I updated example
This  is similar to issue1392.
DB50X  v. 0.8.8
HW DM42n
This concerns matrix  calculations and handling of intermediate  results.

1. set `HwFP 5 prec`
2.  `[[1e20 1e20][2e20  1e20]]`  // 26byte array of HwFP
3. `DET`

Result `0`

Which is wrong, pssibly due to
1. intermediate overflow, no check
2. wrong handling of infinity - infinity
3. no final check of  overflow

**Comment by skai111** [comment]
Example updated

**Comment by c3d** [comment]
I checked that this is already fixed on branch `dev`. Specifically, it raises the `Argument Outside Domain` error because it detects an internal overflow. This was fixed when the simplification rules were disabled for infinities, so that we no longer have `X-X=0` apply when `X=inf`.

`Argument Outside Domain` arises from an internal operation that is `inf - inf`, which is undefined. In other words, we are outside of the domain of values where we can compute the determinant. You can check that there was a numerical overflow internally because flag `-25` (`OverflowIndicator`) is set.

You might prefer to have a numerical overflow cause an error instead of setting a flag. For that, you need to set flag `-21` (i.e. `OverflowError`), and then you get a `Numerical overflow` error from the `Det` operation.

The default to have flag `-21` clear by default is debatable, but the choice here is to follow what the HP50G does.
