### ISSUE TITLE
"No solution?" error for Root Solver on DM42

### ISSUE THREAD

**Issue by mapleleafsa** [c3d/DB48X-on-DM42#627]
The root solver returns a a "No Solution?" error on a DM42 unless the guess answer is close to the solution.  For example:
'X^3=2"
'X"
0

Returns "-error: No solution?"  "X:0"

**Comment by c3d** [comment]
The problem is with the default values for settings, which were incorrectly transcribed when settings were reworked.

- The default for `SolverPrecision` is 34, which is all digits. It's very hard
  to get the last digit. The value before reworking the settings is 24. With
  some experiment, it looks like the setting should be clamped to 32 digits, to
  make sure that we have a chance to get the result.

- The default for 'SolverIterations' is 10, which is much too small. It was 1000
  before the refactoring.

**Comment by mapleleafsa** [comment]
Got it.  Working perfectly! - Merci.

Well done for this amazing project.  The DB48X is now my main calculator. 

Would it by possible to implement the "SOLVR" environment of the HP48 to solve multi-variables equations? (like the one that can be accessed by storing an algebraic formula in 'EQ' and running <<30 MENU>>).
