### ISSUE TITLE
v0.7.3 EquationName error:

### ISSUE THREAD

**Issue by guirossibrum** [c3d/DB48X-on-DM42#882]
Hello Christophe, When opening the Equation library and clicking on  one of the equations, I get EquationName error: Too many open files. I erased the calculator and reinstalled and same error occurs.
On line 1 of the stack I have PerfectGas:P.V=n.G.T.
The error does not go away after that. I have only been able to restore with the rest button in the back.

please let me know if you need additional info.

thank you

**Comment by c3d** [comment]
No additional information needed, I can easily reproduce, and I have a hunch where this comes from.

Fun fact: the DM42 filesystem is configured so that you can only open one file at a time. I suspect that for an equation containing a constant, I am currently opening two files at the same time, `equations.csv` and `constants.csv`.
