### ISSUE TITLE
"Bad argument type" on stack when entering partial DMS values

### ISSUE THREAD

**Issue by mahi2003** [c3d/DB48X-on-DM42#984]
I was playing with degrees-minutes-seconds entry with double period and by accident I did not enter the degrees:

`.` `30` `.` `ENTER` → `Bad argument type` `0°00'00"`

The "Bad argument type" appears on stack level 1, left from 0°00'00". I've not seen such an error before.

Pressing the down arrow to edit the stack item throws _"mod error: Bad argument type"_.

If this syntax is not permitted, there should have been a blocking error during entry. No bad objects should get on the stack.

**Update:** A similar issue exists with the seconds:

`1` `.` `30` `.` `.` `ENTER` → `Bad argument type` `0°00'00"`

And while I can't do it with the `.` key, I can also reproduce it for the minutes by using the `'` from the `CHAR` menu:

`1` `.` `.` `'` `ENTER` → `Bad argument type` `0°00'00"`

---

PS: Not related, but simple calculations (addition/subtraction) with dms values seem to be pretty slow, even on USB power.

**Comment by c3d** [comment]
The `Bad argument type` that shows next to a stack object is because you found a way to enter a unit object that has a `dms` unit but does not have a real value.

The value is a name like `°30`. Trying to convert that to integer values is what results in the `Bad argument type` error.

Errors showing on the side of a stack item is a protection to show unexpected errors happening when rendering an object. This is necessary for the few cases where an error may be legitimate, e.g. getting an `Out of memory` error while rendering a large object.

**Comment by mahi2003** [comment]
✔️ Confirmed fixed in 0.7.9!
