### ISSUE TITLE
Recalling value of `c` with `m` set to `1_kg` gives bad value

### ISSUE THREAD

**Issue by c3d** [c3d/DB48X-on-DM42#988]
When you recall the numerical value of `c` with `m` set to a value with a unit, that value takes precedence and you get something like `299792548_(1/100_kg)/s` on the stack instead of the actual unit.

**Comment by c3d** [comment]
Same result whether you convert with `->Num` or directly recall the value from the constants menu.

**Comment by mahi2003** [comment]
Same issue when using `m/s` from the units menu:

`1` `m/s` → `1_(1/100_kg)/s`

In fact, it seems to happen whenever meter (_m) is involved with another unit (or even itself):

`1_m` `1_s` `÷` → :x: `1_(1/100_kg)/s`
`1_m` `1_s` `×` → :x: `1_s∙(1/100_kg)`
`1_m` `1_kN` `×` → :x: `1_kN∙(1/100_kg)`
`1_m` `1_m` `×` → :x: `1_1/10000_kg²`

However, as soon as you use a prefix for meter, the problem no longer occurs:

`1_km` `1_s` `÷` → ✔️ `1_km/s`
`1_cm` `1_s` `×` → ✔️ `1_cm∙s`
`1_km` `1_kN` `×` → ✔️ `1_km∙kN`
`1_km` `1_km` `×` → ✔️ `1_km²`

**Update:** Discard that last comment... There's more going on:

`1_km` `1_h` `÷` → :x: `1_km∙(1/100_kg‾¹)`

**Comment by mahi2003** [comment]
Interestingly, the issue resolved itself after resetting the calculator (including recalling c and `→Num`). Doing so also fixed #987 for me.

**Comment by mahi2003** [comment]
I found what starts breaking the units: Variables with the same name as a unit!

1. Reset calculator
3. `1` `m/s` → `1_m/s` ✔️ Step is optional, but confirms that at this time DB48/50X operates correctly
4. `10_g` `'m'` `STO`
5. `1` `m/s` → :x: `1_(10_g)/s`

If you delete variable m, the issue is gone again:

6. `'m'` `Purge`
7. `1` `m/s` → `1_m/s` ✔️

DB48/50X is substituting units with variables: 1_(<sub>unit</sub>m)/(<sub>unit</sub>s) becomes 1_(<sub>variable</sub>m)/(<sub>unit</sub>s) when variable m exists.

Note that it is not doing that when there are no operations on the unit: `1_m` does not become `1_(10_g).

I don't know whether this bug is the same as #987 and the _"No solution"_ issue you noticed in the 0.7.8 demo video at 19:15-19:35, but both seem to be related to units, so there is a good chance...

**Comment by mahi2003** [comment]
**Update:** I just realized you already knew all that. I misread your first sentence and was blind for the issue title. I feel so stupid now...

**Comment by c3d** [comment]
Duplicate of #969, closing.
